Vehicle/Controllers/CarsVehicleController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Vehicle.Models;

namespace Vehicle.Controllers
{
    public class CarsVehicleController : Controller
    {
        private BusinessLayer bl = new BusinessLayer();
       


        // GET: CarsVehicle/Details/5
        public ActionResult Details(long? id)
        {
            try
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                var vehicle = bl.GetVehicle(id);
                if (vehicle == null)
                {
                    return HttpNotFound();
                }
                return View(vehicle);
            }
            catch (Exception)
            {
                return new HttpStatusCodeResult(HttpStatusCode.InternalServerError);
            }
        }


        // GET: CarsVehicle/Create
        public ActionResult Create()
        {
            try
            {
                return View();
            }
            catch (Exception)
            {
                return new HttpStatusCodeResult(HttpStatusCode.InternalServerError);
            }
        }

        // POST: CarsVehicle/Create
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "VehicleID,VehicleType,Make,Model,Engine,Doors,Wheels,Type")] Car car)
        {
            try
            {

                if (ModelState.IsValid)
                {

                    bl.Add_Car(car);
                    return RedirectToAction("Details?id="+car.VehicleID);
                }

                return View(car);
            }
            catch (Exception)
            {
                return new HttpStatusCodeResult(HttpStatusCode.InternalServerError);
            }
        }


    }
}

Vehicle/Controllers/VehicleTypesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Vehicle.Models;

namespace Vehicle.Controllers
{
    public class VehicleTypesController : Controller
    {
        private BusinessLayer bl = new BusinessLayer();

        // GET: VehicleTypes
        public ActionResult Index()
        {
            try
            {
                var types = bl.GetV_VehicleTypes();

                return View(types);
            }
            catch(Exception)
            {
                return new HttpStatusCodeResult(HttpStatusCode.InternalServerError);
            }
        }

    }
}

Vehicle/Views/CarsVehicle/Create.cshtml
@model Vehicle.Models.Car

@{
    ViewBag.Title = "Create A Car";
}

<h2>Create A Car</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
       
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        
        <div class="form-group">
            @Html.LabelFor(model => model.Make, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Make, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Make, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Model, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Model, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Model, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Engine, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Engine, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Engine, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Doors, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Doors, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Doors, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Wheels, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Wheels, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Wheels, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Type, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Type, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Type, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-sm btn-primary" />
            </div>
        </div>
    </div>
}


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Vehicle/Views/CarsVehicle/Details.cshtml
@model Vehicle.Models.Car

@{
    ViewBag.Title = "Details";
}

<h2>Car Details</h2>

<div>
    <table>
        <tr class="table-borderless;" >
            <th>
                @Html.DisplayNameFor(model => model.Make)
            </th>

            <td>
                @Html.DisplayFor(model => model.Make)
            </td>
        </tr>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Model)
            </th>

            <td>
                @Html.DisplayFor(model => model.Model)
            </td>
        </tr>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Engine)
            </th>

            <td>
                @Html.DisplayFor(model => model.Engine)
            </td>
        </tr>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Doors)
            </th>

            <td>
                @Html.DisplayFor(model => model.Doors)
            </td>
        </tr>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Wheels)
            </th>

            <td>
                @Html.DisplayFor(model => model.Wheels)
            </td>
        </tr>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Type)
            </th>

            <td>
                @Html.DisplayFor(model => model.Type)
            </td>

        </tr>
    </table>
</div>
<br />
<br />
<br />
<p>
    @Html.ActionLink("Add more Vehicles", "/Index", "VehicleTypes")
</p>